sudo: false

language: node_js

node_js:
  - "7"

os:
  - linux
  - macosx
  - windows

matrix:
  include:
  - node_js: 7
    os: linux
    env: USE_NPM=true
  - node_js: 6
    os: linux
  - node_js: 4
    os: linux

cache:
  yarn: true

before_install:
  - if [ "$USE_NPM" == "true" ]; then rm yarn.lock; fi

before_script:
  - if git status | grep -q "modified.   \.travis\.yml"; then echo "Dirty yarn.lock"; exit 1; fi

script:
  - grunt

notifications:
  irc:
    channels:
    - "irc.hackint.org#freifunkR"
    - "irc.hackint.org#meshviewer"
    template:
      - "%{repository_slug}#%{build_number} %{message} (%{branch} - %{commit}: %{commit_subject})"
      - "Change view : %{compare_url} Build details : %{build_url} %{pull_request_url}"
    nick: ci
    use_notice: true
